In [1]:

import pandas as pd
import numpy as np
import sys
from credentials import *
import itertools
from scipy import stats

/Users/jiachi/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [84]:
def get_all_combinations(array):
    all_combinations = []
    for r in range(1, len(array) + 1):
        combinations = itertools.combinations(array, r)
        all_combinations.extend(combinations)
    return all_combinations


def get_stats(df, group_by):
    # stats = {}
    # stats['Mean outcome'] = group['outcome'].mean()
    # stats['Count'] = group['outcome'].count()
    # # stats['Count of non-response'] = group['reward'].isnull().sum()
    # # stats['% of non-response'] = round(group['reward'].isnull().mean() * 100,2)

    df = df.groupby(group_by) \
       .agg(count=('outcome', 'size'), 
            mean=('outcome', lambda x: round(x.mean(), 3)), 
            count_of_non_response=('outcome', lambda x: x.isnull().sum()),
            percent_of_non_response=('outcome', lambda x: round((x.isnull().mean() * 100), 3))) \
       .reset_index()
    
    df = df.rename(columns={
        "count": "Count",
        "mean": "Mean",
        "count_of_non_response": "Count of non-response",
        "percent_of_non_response": "% of non-response"
    })
    return df

In [85]:
df = pd.read_csv('~/Desktop/DataArrow/dataset/4v4var.csv')
df

,_id,user,outcome,where,policy,treatment,treatment.timestamp,outcome.timestamp,is_uniform,TakeShower,TakeShower.timestamp,HappyOrNot,HappyOrNot.timestamp,wantToTravel,wantToTravel.timestamp,haveLunch,haveLunch.timestamp
0,648879d5e3bb62aff3a95559,sim_user_1,NaN,NaN,ThompsonSamplingContextual,version3,2023-06-13 10:14:45.934,NaN,NaN,1,2023-06-13 10:12:39.239,1,2023-06-13 10:13:48.438,1,2023-06-13 10:12:38.998,1,2023-06-13 10:12:39.127
1,648879d9e3bb62aff3a9566d,sim_user_1,NaN,NaN,ThompsonSamplingContextual,version3,2023-06-13 10:14:49.243,NaN,NaN,1,2023-06-13 10:12:39.239,1,2023-06-13 10:13:48.438,1,2023-06-13 10:12:38.998,1,2023-06-13 10:12:39.127
2,648879dbe3bb62aff3a95731,sim_user_1,NaN,NaN,ThompsonSamplingContextual,version3,2023-06-13 10:14:51.977,NaN,NaN,1,2023-06-13 10:12:39.239,1,2023-06-13 10:13:48.438,1,2023-06-13 10:12:38.998,1,2023-06-13 10:12:39.127
3,648879dde3bb62aff3a957b1,sim_user_1,1.0,NaN,ThompsonSamplingContextual,version2,2023-06-13 10:14:53.924,2023-06-13 10:14:56.344,NaN,1,2023-06-13 10:12:39.239,1,2023-06-13 10:13:48.438,1,2023-06-13 10:12:38.998,1,2023-06-13 10:12:39.127
4,648879e2e3bb62aff3a958e3,sim_user_1,1.0,NaN,ThompsonSamplingContextual,version2,2023-06-13 10:14:58.565,2023-06-13 10:15:02.917,NaN,1,2023-06-13 10:12:39.239,1,2023-06-13 10:13:48.438,1,2023-06-13 10:12:38.998,1,2023-06-13 10:12:39.127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816,64887a27e3bb62aff3a96934,sim_user_99,NaN,NaN,ThompsonSamplingContextual,version3,2023-06-13 10:16:07.023,NaN,NaN,1,2023-06-13 10:15:43.812,1,2023-06-13 10:15:43.216,0,2023-06-13 10:15:43.445,0,2023-06-13 10:15:43.595
1817,64887a2ce3bb62aff3a96a39,sim_user_99,0.0,NaN,ThompsonSamplingContextual,version4,2023-06-13 10:16:12.791,2023-06-13 10:16:14.381,NaN,1,2023-06-13 10:15:43.812,1,2023-06-13 10:15:43.216,0,2023-06-13 10:15:43.445,0,2023-06-13 10:15:43.595
1818,64887a35e3bb62aff3a96c03,sim_user_99,0.0,NaN,ThompsonSamplingContextual,version3,2023-06-13 10:16:21.169,2023-06-13 10:16:22.658,NaN,1,2023-06-13 10:15:43.812,1,2023-06-13 10:15:43.216,0,2023-06-13 10:15:43.445,0,2023-06-13 10:15:43.595
1819,64887a3ae3bb62aff3a96d0a,sim_user_99,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:16:26.160,2023-06-13 10:16:27.651,NaN,1,2023-06-13 10:15:43.812,1,2023-06-13 10:15:43.216,0,2023-06-13 10:15:43.445,0,2023-06-13 10:15:43.595
1820,64887a40e3bb62aff3a96e38,sim_user_99,0.0,NaN,ThompsonSamplingContextual,version2,2023-06-13 10:16:32.151,2023-06-13 10:16:35.632,NaN,1,2023-06-13 10:15:43.812,1,2023-06-13 10:15:43.216,0,2023-06-13 10:15:43.445,0,2023-06-13 10:15:43.595

In [92]:
# test
get_stats(df, ['treatment'])

  treatment  Count   Mean  Count of non-response  % of non-response
0  version1    527  0.505                    153             29.032
1  version2    200  0.411                     49             24.500
2  version3    512  0.474                    149             29.102
3  version4    582  0.486                    181             31.100

In [5]:
def filter_dataframe(df, filter_dict):
    
    # Using boolean indexing
    conditions = [(df[column].isin([filter_dict[column]])) for column in filter_dict]
     # conditions[0] only filter the fist condition, if you want to apply all conditons, check next line
    final_condition = np.all(conditions, axis=0)
    filtered_df_boolean = df[final_condition].reset_index(drop=True) # TODO: why conditions[0]? - solved
    
    return filtered_df_boolean
    # return filtered_df_boolean

In [14]:
# test
filter_dict = {'treatment': 'version1', 'outcome': 1}
conditions = [(df[column].isin([filter_dict[column]])) for column in filter_dict]
final_condition = np.all(conditions, axis=0)

In [13]:
# test
filter_dict = {'treatment': 'version1', 'outcome': 1}
conditions = [(df[column].isin([filter_dict[column]])) for column in filter_dict]
final_condition = np.all(conditions, axis=0)

In [15]:
filtered_df_boolean = df[final_condition].reset_index(drop=True)
filtered_df_boolean

,_id,user,outcome,where,policy,treatment,treatment.timestamp,outcome.timestamp,is_uniform,TakeShower,TakeShower.timestamp,HappyOrNot,HappyOrNot.timestamp,wantToTravel,wantToTravel.timestamp,haveLunch,haveLunch.timestamp
0,648879ebe3bb62aff3a95b61,sim_user_10,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:15:07.773,2023-06-13 10:15:09.136,NaN,1,2023-06-13 10:14:58.468,0,2023-06-13 10:14:58.088,1,2023-06-13 10:14:58.196,1,2023-06-13 10:14:58.342
1,64887a0be3bb62aff3a96347,sim_user_10,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:15:39.072,2023-06-13 10:15:42.501,NaN,1,2023-06-13 10:14:58.468,0,2023-06-13 10:14:58.088,1,2023-06-13 10:14:58.196,1,2023-06-13 10:14:58.342
2,648879dfe3bb62aff3a95825,sim_user_100,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:14:55.639,2023-06-13 10:14:59.922,NaN,0,2023-06-13 10:13:01.131,0,2023-06-13 10:14:33.070,1,2023-06-13 10:13:00.840,0,2023-06-13 10:13:00.953
3,64887a09e3bb62aff3a962d7,sim_user_100,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:15:37.159,2023-06-13 10:15:41.560,NaN,0,2023-06-13 10:13:01.131,0,2023-06-13 10:14:33.070,1,2023-06-13 10:13:00.840,0,2023-06-13 10:13:00.953
4,64887a25e3bb62aff3a968fb,sim_user_11,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:16:05.815,2023-06-13 10:16:07.317,NaN,1,2023-06-13 10:15:18.001,1,2023-06-13 10:15:17.598,0,2023-06-13 10:15:17.715,1,2023-06-13 10:15:17.856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,64887a01e3bb62aff3a960f8,sim_user_98,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:15:29.631,2023-06-13 10:15:31.011,NaN,0,2023-06-13 10:15:00.929,0,2023-06-13 10:15:00.527,1,2023-06-13 10:15:00.646,1,2023-06-13 10:15:00.806
185,64887a41e3bb62aff3a96e93,sim_user_98,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:16:33.841,2023-06-13 10:16:35.362,NaN,0,2023-06-13 10:15:00.929,0,2023-06-13 10:15:00.527,1,2023-06-13 10:15:00.646,1,2023-06-13 10:15:00.806
186,648879fee3bb62aff3a96038,sim_user_99,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:15:26.599,2023-06-13 10:15:29.997,NaN,0,2023-06-13 10:15:17.134,0,2023-06-13 10:15:16.756,1,2023-06-13 10:15:16.882,0,2023-06-13 10:15:16.980
187,64887a08e3bb62aff3a962b4,sim_user_99,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:15:36.559,2023-06-13 10:15:37.906,NaN,0,2023-06-13 10:15:17.134,0,2023-06-13 10:15:16.756,1,2023-06-13 10:15:16.882,0,2023-06-13 10:15:16.980
188,64887a3ae3bb62aff3a96d0a,sim_user_99,1.0,NaN,ThompsonSamplingContextual,version1,2023-06-13 10:16:26.160,2023-06-13 10:16:27.651,NaN,1,2023-06-13 10:15:43.812,1,2023-06-13 10:15:43.216,0,2023-06-13 10:15:43.445,0,2023-06-13 10:15:43.595

In [6]:
# added statistical power
from statsmodels.stats.power import FTestAnovaPower

def calculate_statistical_power(df, outcome_var):
    nobs = len(df[outcome_var])  # total number of observations
    n_groups = df[outcome_var].nunique()  # unique outcome

    # Calculate effect size (eta squared)
    ss_total = np.sum((df[outcome_var] - np.mean(df[outcome_var]))**2)
    ss_explained = (np.sum(df.groupby('treatment')[outcome_var].count() *
                           (df.groupby('treatment')[outcome_var].mean() - np.mean(df[outcome_var]))**2))
    eta_squared = ss_explained / ss_total

    # Perform power analysis
    analysis = FTestAnovaPower()
    # Statistical Power calculations F-test for one factor balanced ANOVA
    # This is based on Cohen’s f as effect size measure.
    power = analysis.solve_power(eta_squared, nobs=nobs, alpha=0.05, k_groups=n_groups)

    return round(power, 3)  # return rounded power

In [71]:
df["outcome"].count()

1289

In [70]:
df["outcome"].mean()

0.4794414274631497

In [102]:
# Final function
def basic_reward_summary_table(df, selectedVariables, selectedAssigners = []):

    result_df = None
    data = df
    # filter out selected assigners
    if len(selectedAssigners) > 0:
        data = df[df['assigner'].isin(selectedAssigners)]
    all_combs = get_all_combinations(selectedVariables)
    if len(selectedVariables) == 0:
        result_df = get_stats(data, ['treatment'])
    else:
        # group by treatment and all combinations of selected variables
        group_bys = [['treatment']] + [['treatment'] + list(comb) for comb in all_combs]
        grouped_dfs = []
        for group in group_bys:
            grouped = get_stats(data, group)
            grouped_dfs.append(grouped)

        result_df = pd.concat(grouped_dfs, axis=0, ignore_index=True)
    desired_columns = [col for col in result_df.columns if col not in ['Count', 'Mean','Count of non-response',"% of non-response"]] + ['Count', 'Mean','Count of non-response',"% of non-response"]
    
    # Reorder the columns
    result_df = result_df[desired_columns]
    result_df = result_df.replace(np.nan, -np.inf, regex=True)
    result_df = result_df.sort_values(by= selectedVariables + ['treatment'], ascending=True)
    result_df = result_df.replace(-np.inf, '', regex=True) # not sure how to sort ascendingly but put empty on top.
    # temporarily fill empty strings or NaN values with a value that's guaranteed to be smaller than all other values during the sort, and then replace it back to the empty string afterwards. In this case, -np.inf serves that purpose. 


    unique_versions = result_df['treatment'].unique()
    # Get the filter conditions -> TODO: since the table won't have many rows, it is fine to do a for loop? - solved
        
    filter_conditions = []
    for comb in all_combs:
        comb = list(comb)
        filter_empty = result_df[comb].ne('').all(axis=1) 
        unique_combinations = result_df[filter_empty].drop_duplicates(subset=comb)[comb].to_dict(orient='records')
        filter_conditions.extend(unique_combinations)
    
    
    # ! Use ANOVA to calculate p-value and power 
    for filter_condition in filter_conditions:
        filtered_df = filter_dataframe(df, filter_condition)
        outcomes = [filtered_df[filtered_df['treatment'] == version]['outcome'].dropna() for version in unique_versions]
        f_value, p_value = stats.f_oneway(*outcomes)
        
        # calculate power for the filtered dataframe
        power = calculate_statistical_power(filtered_df, 'outcome')
        
        for index, row in result_df.iterrows():
            if all(row[key] == value for key, value in filter_condition.items()):
                result_df.loc[index, 'P value'] = round(p_value,3)
                result_df.loc[index, 'Power'] = power

    # ! calculate p value, power for the whole dataset.
    outcomes = [df[df['treatment'] == version]['outcome'].dropna() for version in unique_versions]
    f_value, p_value = stats.f_oneway(*outcomes)
    power = calculate_statistical_power(df, 'outcome')
    for index, row in result_df.iterrows():
        if all(row[key] == "" for key in selectedVariables):
            result_df.loc[index, 'P value'] = round(p_value,3)
            result_df.loc[index, 'Power'] = power
            
    # change P-value to string
    result_df["P value"] = result_df["P value"].astype("string")
    
    
    
    # Calculate overall statistics
    outcomes = [df[df['treatment'] == version]['outcome'].dropna() for version in unique_versions]
    f_value, overall_p_value = stats.f_oneway(*outcomes)
    
    # Create a new DataFrame for overall statistics with no version
    overall_df = pd.DataFrame({"treatment": ["No Version"], 
                               "Count": [df["outcome"].size],# size is the count including NA valuess
                               "Mean": [round(df['outcome'].mean(),3)],
                               "Count of non-response": [df['outcome'].isnull().sum()],
                               "% of non-response": [round(df['outcome'].isnull().mean() * 100,3)],
                               "P value": [round(overall_p_value,3)],
                               "Power": [calculate_statistical_power(df, 'outcome')]})

    # Append the overall statistics DataFrame to the result DataFrame
    result_df = pd.concat([result_df, overall_df], ignore_index=True)
    # Fill NaN with ""
    result_df = result_df.fillna("")
    result_df = result_df.reindex([result_df.index[-1]] + list(result_df.index[:-1]))
    return result_df

In [103]:
basic_reward_summary_table(df, ['HappyOrNot','wantToTravel'])

,treatment,HappyOrNot,wantToTravel,Count,Mean,Count of non-response,% of non-response,P value,Power
36,No Version,,,1821,0.479,532,29.215,0.263,0.052
0,version1,,,527,0.505,153,29.032,0.263,0.052
1,version2,,,200,0.411,49,24.500,0.263,0.052
2,version3,,,512,0.474,149,29.102,0.263,0.052
3,version4,,,582,0.486,181,31.100,0.263,0.052
4,version1,,0.0,285,0.493,84,29.474,0.583,0.051
5,version2,,0.0,107,0.427,25,23.364,0.583,0.051
6,version3,,0.0,245,0.459,62,25.306,0.583,0.051
7,version4,,0.0,248,0.508,67,27.016,0.583,0.051
8,version1,,1.0,242,0.520,69,28.512,0.325,0.053
9,version2,,1.0,93,0.391,24,25.806,0.325,0.053
10,version3,,1.0,267,0.489,87,32.584,0.325,0.053
11,version4,,1.0,334,0.468,114,34.132,0.325,0.053
12,version1,0.0,,407,0.507,119,29.238,0.088,0.061
13,version2,0.0,,85,0.333,19,22.353,0.088,0.061
14,version3,0.0,,198,0.464,60,30.303,0.088,0.061
15,version4,0.0,,224,0.474,68,30.357,0.088,0.061
16,version1,0.0,0.0,212,0.477,61,28.774,0.735,0.051
17,version2,0.0,0.0,43,0.394,10,23.256,0.735,0.051
18,version3,0.0,0.0,85,0.508,20,23.529,0.735,0.051
19,version4,0.0,0.0,86,0.500,22,25.581,0.735,0.051
20,version1,0.0,1.0,195,0.540,58,29.744,0.036,0.087
21,version2,0.0,1.0,42,0.273,9,21.429,0.036,0.087
22,version3,0.0,1.0,113,0.425,40,35.398,0.036,0.087
23,version4,0.0,1.0,138,0.457,46,33.333,0.036,0.087
24,version1,1.0,,120,0.500,34,28.333,0.971,0.050
25,version2,1.0,,115,0.471,30,26.087,0.971,0.050
26,version3,1.0,,314,0.480,89,28.344,0.971,0.050
27,version4,1.0,,358,0.494,113,31.564,0.971,0.050
28,version1,1.0,0.0,73,0.540,23,31.507,0.479,0.053
29,version2,1.0,0.0,64,0.449,15,23.438,0.479,0.053
30,version3,1.0,0.0,160,0.432,42,26.250,0.479,0.053
31,version4,1.0,0.0,162,0.513,45,27.778,0.479,0.053
32,version1,1.0,1.0,47,0.444,11,23.404,0.767,0.051
33,version2,1.0,1.0,51,0.500,15,29.412,0.767,0.051
34,version3,1.0,1.0,154,0.533,47,30.519,0.767,0.051
35,version4,1.0,1.0,196,0.477,68,34.694,0.767,0.051

In [21]:
# Function description
# First, need to filter df by selectedVersion, selectedVariable, selectedPolicy.
# Secondly, format the rewardTimestamp to a certain format by per ("day", "week", "month", "year"). (this can be done later)
# group by the formatted rewardTimestamp, calculate the mean of the outcome, stderros, 25, 75 cis... (you can choose how we interpret the error bars)
# Return is a dataframe that's like:
# time, mean, errorBarEnd1, errorBarEnd2
# ! per_day need to be defined as day - 'd', Month - 'm', Year - 'y', Week - 'w'

def average_reward_for_one_version(df, selectedVersion, selectedVariable, selectedPolicy, per_day="d"):
    # Filter dataframe
    filtered_df = df[(df['treatment'] == selectedVersion) &  
                     (df['policy'] == selectedPolicy)]
    # Select columns
    filtered_df = filtered_df[['treatment', 'policy', 'outcome', 'outcome.timestamp', selectedVariable]]

    # Format rewardTimestamp
    filtered_df['outcome.timestamp'] = pd.to_datetime(filtered_df['outcome.timestamp'])
    filtered_df['outcome.timestamp'] = filtered_df['outcome.timestamp'].dt.to_period(per_day)
    
    # Group by rewardTimestamp and calculate mean and standard error of outcome
    result_df = round(filtered_df.groupby('outcome.timestamp').agg({
        'outcome': ['mean', 'std', 'count', lambda x: x.quantile(0.25), lambda x: x.quantile(0.75)]
    }),3)
    # reset index
    result_df.reset_index(inplace=True)
    
    # Rename columns
    result_df.columns = ['time','mean', 'std', 'count', '25th quantile', '75th quantile']

    return result_df

In [22]:
df = pd.read_csv('~/Desktop/DataArrow/dataset/4v4var.csv')
policy = 'ThompsonSamplingContextual'
version = 'version1'
variable = "HappyOrNot"
per_day = "d"
result_df = average_reward_for_one_version(df, version, variable, policy, per_day)
result_df

         time   mean    std  count  25th quantile  75th quantile
0  2023-06-13  0.505  0.501    374            0.0            1.0